# Generated by Django 4.1 on 2022-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(choices=[('natural_person', 'jismoniy shaxs'), ('Legal_entity', 'yuridik shaxs')])),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('payment', models.PositiveIntegerField()),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
