# Generated by Django 4.1 on 2022-08-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_remove_student_univer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='univer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsor.university'),
        ),
    ]
