# Generated by Django 4.1 on 2022-08-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_alter_student_univer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='univer',
        ),
    ]
