# Generated by Django 4.1 on 2022-08-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_remove_student_univer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
