# Generated by Django 4.1 on 2022-08-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('degree', models.TextField(choices=[('bachelor', 'bakalavr'), ('master', 'magistr')])),
                ('contract', models.PositiveIntegerField()),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.university')),
            ],
        ),
    ]
