# Generated by Django 4.1 on 2022-08-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='univer',
            new_name='university',
        ),
    ]
