# Generated by Django 4.1 on 2022-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0010_alter_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='choice',
            field=models.TextField(choices=[('natural_person', 'Natural person'), ('legal_entity', 'Legal entity')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.TextField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')]),
        ),
    ]
