# Generated by Django 4.1 on 2022-08-10 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0011_alter_sponsor_choice_alter_student_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_sum', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.TextField(choices=[('new', 'New'), ('moderation', 'Moderation'), ('approved', 'Approved'), ('canceled', 'Canceled')])),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsor')),
            ],
        ),
    ]
