# Generated by Django 4.1 on 2022-08-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0014_alter_sponsor_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstothestudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors_student', to='sponsor.sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsorstothestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors_student', to='sponsor.student'),
        ),
    ]
