# Generated by Django 4.1 on 2022-08-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0016_alter_sponsorstothestudent_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstothestudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors_student', to='sponsor.sponsor'),
        ),
    ]
