# Generated by Django 4.1 on 2022-08-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0017_alter_sponsorstothestudent_sponsor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsorstothestudent',
            unique_together={('student', 'sponsor')},
        ),
    ]
