# Generated by Django 4.1 on 2022-08-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0019_remove_sponsorintroduction_spent_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorintroduction',
            name='sponsor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_introduction', to='sponsor.sponsor'),
        ),
    ]
